// <auto-generated />
using KidsMath.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KidsMath.Persistence.Migrations
{
    [DbContext(typeof(KidsMathDbContext))]
    [Migration("20260605120000_AddTemplateThemeId")]
    partial class AddTemplateThemeId
    {
    }
}
